---
jobs:
  include:
    - stage: test
      services:
        - docker
      install:
        - docker build -t borgmatic .
      script:
        - docker run --rm borgmatic borg --version | grep 'borg [0-9\.]\{1,\}'
        - "docker run --rm borgmatic  --help | grep --quiet 'usage: borgmatic .*'"

notifications:
  webhooks: https://hooks.microbadger.com/images/monachus/borgmatic/AMmMl53vvtRwli-9St5egV6bS7g=
